version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    labels: ["dependencies", "security"]
    reviewers:
      - "beqs1"
    assignees:
      - "beqs1"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        versions: ["<3.4.5"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]
    reviewers:
      - "beqs1"
    assignees:
      - "beqs1"
