name: Checkov IaC Scan

on:
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '15 2 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov (Dockerfile + compose)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: dockerfile,compose
          quiet: true
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

