name: OSV Scanner

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run OSV Scanner
        uses: google/osv-scanner/actions/scan-repository@main
        with:
          scan-args: "--format sarif --output osv-results.sarif"

      - name: Upload OSV SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif
          category: osv-scanner
