name: ZAP API DAST

on:
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '45 2 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  zap-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start stack (db + app)
        env:
          SECURITY_ENC_MASTER_KEY: dev-dev-dev-dev-dev-dev-dev-dev
          SECURITY_ENC_ACTIVE_KEY_ID: k1
          SECURITY_JWT_SECRET: dev-jwt-secret-please-change
          POSTGRES_DB: emr
          POSTGRES_USER: emr
          POSTGRES_PASSWORD: emrpass
        run: |
          docker compose up -d --build

      - name: Wait for health
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8080/actuator/health >/dev/null; then
              echo "App is healthy"; exit 0; fi
            sleep 5
          done
          echo "App didn't become healthy in time"; docker compose logs --no-color | tail -n 200; exit 1

      - name: ZAP API Scan (OpenAPI)
        uses: zaproxy/action-api-scan@v0.8.0
        with:
          target: 'http://localhost:8080/v3/api-docs'
          format: openapi
          fail_action: false
          cmd_options: '-a -m 5'

      - name: Upload ZAP API reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-api-report
          path: |
            report_html.html
            report_json.json
            report_md.md
          if-no-files-found: ignore

      - name: Tear down
        if: always()
        run: docker compose down -v
